language: bash
services: docker
before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
stages:
  - build
jobs:
  include:
    - stage: build
      name: "Dev build"
      if: branch = master AND tag IS empty
      script:       
        - docker build -t vasyahuyasa/ushtr:dev .
        - docker push vasyahuyasa/ushtr:dev
    - stage: build
      name: "Release build"
      if: tag IS present
      script:
        - docker build -t vasyahuyasa/ushtr:latest .        
        - docker push vasyahuyasa/ushtr:latest
        - docker tag vasyahuyasa/ushtr:latest vasyahuyasa/ushtr:$TRAVIS_TAG
        - docker push vasyahuyasa/ushtr:TRAVIS_TAG
