version: '3.1'

services:
  pg1:
    image: postgres:11-alpine
    restart: always
    volumes:
    - ./data/pg1/data:/var/lib/postgresql/data
    - ./data/pg1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
    - env/.env_postgres
    ports:
    - "5401:5432"


  pg2:
    image: postgres:11-alpine
    restart: always
    volumes:
    - ./data/pg2/data:/var/lib/postgresql/data
    - ./data/pg2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
    - env/.env_postgres
    ports:
    - "5402:5432"
